image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build

job-build-main-branchs:
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - export IMAGE_TAG=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - export IMAGE_TAG_LATEST=$CI_REGISTRY_IMAGE:latest
  stage: build
  script:
    - docker build -t ${IMAGE_TAG}-waiter .
    - docker push ${IMAGE_TAG}-waiter

  only:
    - master
